##
##    Project: SDDC.Lab
##    Authors: Luis Chanu & Rutger Blom
##   Filename: playbooks/federateNsxT0BGPNeighbors.yml
##
##      Notes: The purpose of this playbook is configure BGP Neighbors on the Federated Tier-0 Gateway.
##
---
- hosts: localhost
  name: federateNsxT0BGPNeighbors.yml
  vars:
    LOCAL_T0BGPNeighbors_Template: "{{ Target.TemplateFolder }}/vars_NSXT_T0BGPNeighbors.j2"
  tasks:
    - name: federateNsxT0BGPNeighbors_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"

    - name: Display error message if Pod-XXX-Config file is not valid or provided
      ansible.builtin.pause:
        seconds: 5
        prompt: |
          *****************************************************************************************************
          ****************************************** ERROR MESSAGE ********************************************
          *****************************************************************************************************

            A valid "Pod-XXX-Config.yml" file is required in order for this playbook to run.

            Please verify:
            ==============
              1) You supplied a valid Pod-XXX-Config.yml file via the ansible-playbook -e "@Pod-XXX-Config.yml"
                 command-line option.  Here is an example of a how to load a Pod-XXX-Config.yml file that is
                 located in your home directory:
                                    ansible-playbook -e "@~/Pod-XXX-Config.yml" deploy.yml

              2) The Pod-XXX-Config.yml file provided was created using the playbooks/CreatePodConfig.yml script.
                 All Pod configuration files used to deploy labs MUST be generated using that script.

              3) You included the proper path with the "-e" option to the Pod-XXX-Config.yml file.

              4) You prefaced the file name in the "-e" option with a '@', as shown in the example above.

          *****************************************************************************************************
      when:
        - Valid_Pod_Config_File is not defined

    - name: Exit Ansible playbook if Pod-XXX-Config.yml file is not valid or provided
      ansible.builtin.meta: end_play
      when: Valid_Pod_Config_File is not defined


    - name: DEBUG -- Display Target Variables (Pause)
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ '%03d'|format(Pod.Number|int) }} ==================================

                                         Ansible Playbook: {{ ansible_play_name }}

             Nested_NSXT.Component.GlobalManager_VIP.FQDN: {{ Nested_NSXT.Component.GlobalManager_VIP.FQDN }}
           Nested_NSXT.Component.GlobalManager_VIP.VMName: {{ Nested_NSXT.Component.GlobalManager_VIP.VMName }}

                                  Number of BGP Neighbors: {{ Nested_NSXT.Networking.Tier0Gateways[0].BGP.Neighbors | length }}
                                         Neighbor BGP ASN: {{ Nested_NSXT.Networking.Tier0Gateways[0].BGP.Neighbors[0].RemoteASN }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true

    - name: Generate data structure containing the Tier-0 Gateway BGP Neighbors to create
      ansible.builtin.set_fact:
        bgp_neighbors: "{{ lookup('template', LOCAL_T0BGPNeighbors_Template) | from_yaml }}"
      when:
        - Deploy.Product.NSXT.Federation.Enable == true
        - Deploy.Product.NSXT.LocalManager.Deploy == true
        - Deploy.Product.NSXT.Edge.Deploy == true
        - Deploy.Product.NSXT.GlobalManager.SiteCode != SiteCode

    - name: DEBUG -- Display 'bgp_neighbors' data structure
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ====================== Display IP Pools 'bgp_neighbors' Variable ==========================

          Quantity: {{ bgp_neighbors | length }}

          bgp_neighbors (YAML):
            {{ bgp_neighbors | to_nice_yaml(indent=2, width=99999) | indent(2) }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - Deploy.Product.NSXT.Federation.Enable == true
        - Deploy.Product.NSXT.LocalManager.Deploy == true
        - Deploy.Product.NSXT.Edge.Deploy == true
        - Deploy.Product.NSXT.GlobalManager.SiteCode != SiteCode

    - name: Configure BGP Neighbors on Tier-0 Gatweay for Pod
      ansible.builtin.uri:
        url: https://{{ Nested_NSXT.Component.GlobalManager_VIP.FQDN }}/global-manager/api/v1/global-infra/tier-0s/{{ Nested_NSXT.Networking.Tier0Gateways[0].Name }}/locale-services/{{ SiteCode }}/bgp/neighbors/{{ item.display_name }}
        url_username: "{{ Nested_NSXT.Credential.admin.Name }}"
        url_password: "{{ Nested_NSXT.Credential.admin.Password }}"
        validate_certs: "{{ Common.PKI.ValidateCerts }}"
        timeout: 15
        force_basic_auth: yes
        method: PATCH
        body_format: json
        body: "{{ item | to_json }}"
        return_content: yes
        status_code: 200
      register: result
      until: result.status == 200
      retries: 12
      delay: 10
      loop: "{{ bgp_neighbors }}"
      when: 
        - Deploy.Product.NSXT.Federation.Enable == true
        - Deploy.Product.NSXT.LocalManager.Deploy == true
        - Deploy.Product.NSXT.Edge.Deploy == true
        - Deploy.Product.NSXT.GlobalManager.SiteCode != SiteCode
