---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: List Transport Nodes
      nsxt_transport_nodes_facts:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
      check_mode: yes
